name: First Job Example
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4.1.0

      # Greet the user
      - name: Greet the user
        run: echo "Hello, world from ${{ github.actor }}!"
        shell: bash

      # Display branch information
      - name: Show branch
        run: |
          echo "Current branch is '${{ github.ref }}'."
